'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ClinicMaster.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''use ClinicMaster
        '''go
        '''
        '''-------Disable Constraints------------------------------------------------------------------
        '''
        '''--------------------------------------------------------------------------------------------
        '''---------------ARTRegimen-------------------------------------------------------------------
        '''--------------------------------------------------------------------------------------------
        '''
        '''if exists (select * from sysobjects where name = &apos;fkVisitNoARTRegimen&apos;)
        '''	alter table ARTRegimen
        '''	drop co [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property DisableConstraints() As String
            Get
                Return ResourceManager.GetString("DisableConstraints", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''use ClinicMaster
        '''go
        '''
        '''------Enable Constraints-------------------------------------------------------------------
        '''
        '''--------------------------------------------------------------------------------------------
        '''---------------ARTRegimen-------------------------------------------------------------------
        '''--------------------------------------------------------------------------------------------
        '''
        '''if exists (select * from sysobjects where name = &apos;fkVisitNoARTRegimen&apos;)
        '''	alter table ARTRegimen
        '''	drop con [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property EnableConstraints() As String
            Get
                Return ResourceManager.GetString("EnableConstraints", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''/***************************************************************
        '''This Script is a property of ClinicMaster INTERNATIONAL
        '''Un authorised use or ammendment is not permitted
        '''-- Last updated 10/02/2016 by Wilson Kutegeka
        '''***************************************************************/
        '''
        '''use ClinicMaster
        '''go
        '''
        '''------------------------------------------------------------------------------------------------------
        '''---------------------- Functions -&gt; Triggers -&gt; Views ---------------------------------------- [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Utilities() As String
            Get
                Return ResourceManager.GetString("Utilities", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
